name: Build Native Lib

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25b

      # Ini untuk mengatasi file gradlew yang hilang di repo kamu
      - name: Generate Gradle Wrapper
        run: gradle wrapper

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: native-libs-arm64
          path: app/build/intermediates/cmake/release/obj/arm64-v8a/libpairipcore.so
