name: Build Native Lib Direct

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25b

      - name: Compile with Clang (Custom Name)
        run: |
          $ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ \
          -shared -fPIC \
          -static-libstdc++ \
          -o libpairipmod.so \
          native-lib.cpp \
          -llog

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libpairipmod-so
          path: libpairipmod.so
